version: '2'

services:
  websocket:
    image: dhplay/springbootwebsocket:v1.0.0
    restart: always
    container_name: websocket
    hostname: websocket
    ports:
      - "8089:8089"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
